#ifndef NYAS_PIXELS_DEFS_H
#define NYAS_PIXELS_DEFS_H

enum nyas_blend_func {
	NYAS_BLEND_INVALID = 0,
	NYAS_BLEND_ONE,
	NYAS_BLEND_SRC_ALPHA,
	NYAS_BLEND_ONE_MINUS_SRC_ALPHA,
	NYAS_BLEND_ZERO
};

enum nyas_cull_face {
	NYAS_CULL_CURRENT = 0,
	NYAS_CULL_FRONT,
	NYAS_CULL_BACK,
	NYAS_CULL_FRONT_AND_BACK
};

enum nyas_depth_func {
	// TODO: Add as needed.
	NYAS_DEPTH_CURRENT = 0,
	NYAS_DEPTH_LEQUAL,
	NYAS_DEPTH_LESS,
};

enum nyas_texture_flags {
	TF_CHANNELS = 0, // 0 and 1 bits
	TF_CUBE = 1 << 2,
	TF_DEPTH = 1 << 3,
	TF_MIPMAP = 1 << 4,
	TF_FLOAT = 1 << 5,
	TF_TILING = 1 << 6,
	TF_MIN_FILTER_LERP = 1 << 7,
	TF_MAG_FILTER_LERP = 1 << 8,
	TF_MAG_MIP_FILTER_LERP = 1 << 9,
	TF_LINEAR_COLOR = 1 << 10,
	TF_HALF_FLOAT = 1 << 11
};

enum nyas_framebuffer_slots {
	NYAS_SLOT_DEPTH,
	NYAS_SLOT_STENCIL,
	NYAS_SLOT_DEPTH_STENCIL,
	NYAS_SLOT_COLOR0,
	NYAS_SLOT_COLOR1,
	NYAS_SLOT_COLOR2,
	NYAS_SLOT_COLOR3,
	NYAS_SLOT_COLOR4,
	NYAS_SLOT_COLOR5,
};

enum nyas_cube_faces {
	NYAS_CUBE_POS_X,
	NYAS_CUBE_NEG_X,
	NYAS_CUBE_POS_Y,
	NYAS_CUBE_NEG_Y,
	NYAS_CUBE_POS_Z,
	NYAS_CUBE_NEG_Z,
	NYAS_CUBE_FACE_COUNT
};

#endif // NYAS_PIXELS_DEFS_H
