#ifndef NYAS_DEFS_H
#define NYAS_DEFS_H

#include <stddef.h>

#define NYAS_ENUM_INDEX(ENUM_TYPE, ID) (ENUM_TYPE##_##ID - ENUM_TYPE)
#define NYAS_ENUM_FLAG(ENUM_TYPE, ID) (1U << (NYAS_ENUM_INDEX(ENUM_TYPE, ID)))
#define NYAS_ENUM_COUNT(ENUM_TYPE) (NYAS_ENUM_INDEX(ENUM_TYPE, DEFAULT))

typedef int nyas_handle;
typedef int nyas_flags;
typedef int nyas_enum;

typedef enum nyas_enum_ {
	NYAS_NULL,

	NYAS_TEXTURE_TYPE,
	NYAS_TEXTURE_TYPE_2D = NYAS_TEXTURE_TYPE,
	NYAS_TEXTURE_TYPE_2D_ARRAY,
	NYAS_TEXTURE_TYPE_CUBEMAP,
	NYAS_TEXTURE_TYPE_CUBEMAP_ARRAY,
	NYAS_TEXTURE_TYPE_DEFAULT,

	NYAS_TEXTURE_FORMAT,
	NYAS_TEXTURE_FORMAT_DEPTH = NYAS_TEXTURE_FORMAT,
	NYAS_TEXTURE_FORMAT_STENCIL,
	NYAS_TEXTURE_FORMAT_DEPTH_STENCIL,
	NYAS_TEXTURE_FORMAT_R_8,
	NYAS_TEXTURE_FORMAT_RG_8,
	NYAS_TEXTURE_FORMAT_RGB_8,
	NYAS_TEXTURE_FORMAT_RGBA_8,
	NYAS_TEXTURE_FORMAT_SRGB_8,
	NYAS_TEXTURE_FORMAT_SRGBA_8,
	NYAS_TEXTURE_FORMAT_R_16F,
	NYAS_TEXTURE_FORMAT_RG_16F,
	NYAS_TEXTURE_FORMAT_RGB_16F,
	NYAS_TEXTURE_FORMAT_RGBA_16F,
	NYAS_TEXTURE_FORMAT_R_32F,
	NYAS_TEXTURE_FORMAT_RG_32F,
	NYAS_TEXTURE_FORMAT_RGB_32F,
	NYAS_TEXTURE_FORMAT_RGBA_32F,
	NYAS_TEXTURE_FORMAT_DEFAULT,

	NYAS_TEXTURE_FILTER,
	NYAS_TEXTURE_FILTER_LINEAR = NYAS_TEXTURE_FILTER,
	NYAS_TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR,
	NYAS_TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST,
	NYAS_TEXTURE_FILTER_NEAREST,
	NYAS_TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST,
	NYAS_TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR,
	NYAS_TEXTURE_FILTER_DEFAULT,

	NYAS_TEXTURE_WRAP,
	NYAS_TEXTURE_WRAP_CLAMP_EDGE = NYAS_TEXTURE_WRAP,
	NYAS_TEXTURE_WRAP_WHITE,
	NYAS_TEXTURE_WRAP_BLACK,
	NYAS_TEXTURE_WRAP_CLAMP_REPEAT,
	NYAS_TEXTURE_WRAP_CLAMP_MIRROR,
	NYAS_TEXTURE_WRAP_DEFAULT,

	NYAS_TEXTURE_FACE,
	NYAS_TEXTURE_FACE_POS_X = NYAS_TEXTURE_FACE,
	NYAS_TEXTURE_FACE_NEG_X,
	NYAS_TEXTURE_FACE_POS_Y,
	NYAS_TEXTURE_FACE_NEG_Y,
	NYAS_TEXTURE_FACE_POS_Z,
	NYAS_TEXTURE_FACE_DEFAULT,

	NYAS_VERTEX_ATTRIBUTE,
	NYAS_VERTEX_ATTRIBUTE_POSITION = NYAS_VERTEX_ATTRIBUTE,
	NYAS_VERTEX_ATTRIBUTE_NORMAL,
	NYAS_VERTEX_ATTRIBUTE_TANGENT,
	NYAS_VERTEX_ATTRIBUTE_BITANGENT,
	NYAS_VERTEX_ATTRIBUTE_UV,
	NYAS_VERTEX_ATTRIBUTE_COLOR,
	NYAS_VERTEX_ATTRIBUTE_DEFAULT,

	NYAS_DRAW_BLEND,
	NYAS_DRAW_BLEND_ONE = NYAS_DRAW_BLEND,
	NYAS_DRAW_BLEND_SRC_ALPHA,
	NYAS_DRAW_BLEND_ONE_MINUS_SRC_ALPHA,
	NYAS_DRAW_BLEND_ZERO,
	NYAS_DRAW_BLEND_DEFAULT,

	NYAS_DRAW_CULL,
	NYAS_DRAW_CULL_FRONT = NYAS_DRAW_CULL,
	NYAS_DRAW_CULL_BACK,
	NYAS_DRAW_CULL_FRONT_AND_BACK,
	NYAS_DRAW_CULL_DEFAULT,

	NYAS_DRAW_DEPTH,
	NYAS_DRAW_DEPTH_LEQUAL = NYAS_DRAW_DEPTH,
	NYAS_DRAW_DEPTH_LESS,
	NYAS_DRAW_DEPTH_DEFAULT,

	NYAS_DRAW_OP,
	NYAS_DRAW_OP_COLOR_CLEAR = NYAS_DRAW_OP,
	NYAS_DRAW_OP_DEPTH_CLEAR,
	NYAS_DRAW_OP_DEPTH_TEST,
	NYAS_DRAW_OP_DEPTH_WRITE,
	NYAS_DRAW_OP_STENCIL_CLEAR,
	NYAS_DRAW_OP_STENCIL_TEST,
	NYAS_DRAW_OP_STENCIL_WRITE,
	NYAS_DRAW_OP_BLEND,
	NYAS_DRAW_OP_CULL,
	NYAS_DRAW_OP_SCISSOR,
	NYAS_DRAW_OP_DEFAULT,

	NYAS_TEXTURE_TYPE_COUNT = NYAS_TEXTURE_TYPE_DEFAULT - NYAS_TEXTURE_TYPE,
	NYAS_TEXTURE_FORMAT_COUNT = NYAS_TEXTURE_FORMAT_DEFAULT - NYAS_TEXTURE_FORMAT,
	NYAS_TEXTURE_FILTER_COUNT = NYAS_TEXTURE_FILTER_DEFAULT - NYAS_TEXTURE_FILTER,
	NYAS_TEXTURE_WRAP_COUNT = NYAS_TEXTURE_WRAP_DEFAULT - NYAS_TEXTURE_WRAP,
	NYAS_TEXTURE_FACE_COUNT = NYAS_TEXTURE_FACE_DEFAULT - NYAS_TEXTURE_FACE,
	NYAS_VERTEX_ATTRIBUTE_COUNT = NYAS_VERTEX_ATTRIBUTE_DEFAULT - NYAS_VERTEX_ATTRIBUTE,
	NYAS_DRAW_BLEND_COUNT = NYAS_DRAW_BLEND_DEFAULT - NYAS_DRAW_BLEND,
	NYAS_DRAW_CULL_COUNT = NYAS_DRAW_CULL_DEFAULT - NYAS_DRAW_CULL,
	NYAS_DRAW_DEPTH_COUNT = NYAS_DRAW_DEPTH_DEFAULT - NYAS_DRAW_DEPTH,
	NYAS_DRAW_OP_COUNT = NYAS_DRAW_OP_DEFAULT - NYAS_DRAW_OP,

	NYAS_FLAG_NONE = 0,

	NYAS_FLAG_VA_POSITION = NYAS_ENUM_FLAG(NYAS_VERTEX_ATTRIBUTE, POSITION),
	NYAS_FLAG_VA_NORMAL = NYAS_ENUM_FLAG(NYAS_VERTEX_ATTRIBUTE, NORMAL),
	NYAS_FLAG_VA_TANGENT = NYAS_ENUM_FLAG(NYAS_VERTEX_ATTRIBUTE, TANGENT),
	NYAS_FLAG_VA_BITANGENT = NYAS_ENUM_FLAG(NYAS_VERTEX_ATTRIBUTE, BITANGENT),
	NYAS_FLAG_VA_UV = NYAS_ENUM_FLAG(NYAS_VERTEX_ATTRIBUTE, UV),
	NYAS_FLAG_VA_COLOR = NYAS_ENUM_FLAG(NYAS_VERTEX_ATTRIBUTE, COLOR),

	NYAS_FLAG_DO_COLOR_CLEAR = NYAS_ENUM_FLAG(NYAS_DRAW_OP, COLOR_CLEAR),
	NYAS_FLAG_DO_DEPTH_CLEAR = NYAS_ENUM_FLAG(NYAS_DRAW_OP, DEPTH_CLEAR),
	NYAS_FLAG_DO_DEPTH_TEST = NYAS_ENUM_FLAG(NYAS_DRAW_OP, DEPTH_TEST),
	NYAS_FLAG_DO_DEPTH_WRITE = NYAS_ENUM_FLAG(NYAS_DRAW_OP, DEPTH_WRITE),
	NYAS_FLAG_DO_STENCIL_CLEAR = NYAS_ENUM_FLAG(NYAS_DRAW_OP, STENCIL_CLEAR),
	NYAS_FLAG_DO_STENCIL_TEST = NYAS_ENUM_FLAG(NYAS_DRAW_OP, STENCIL_TEST),
	NYAS_FLAG_DO_STENCIL_WRITE = NYAS_ENUM_FLAG(NYAS_DRAW_OP, STENCIL_WRITE),
	NYAS_FLAG_DO_BLEND = NYAS_ENUM_FLAG(NYAS_DRAW_OP, BLEND),
	NYAS_FLAG_DO_CULL = NYAS_ENUM_FLAG(NYAS_DRAW_OP, CULL),
	NYAS_FLAG_DO_SCISSOR = NYAS_ENUM_FLAG(NYAS_DRAW_OP, SCISSOR),
} nyas_enum_;

typedef struct nyas_texture_data {
	void *pixel_buffer;
	ptrdiff_t pixel_buffer_size;
	int lod;        /* level of detail */
	int index;      /* texture arrays only */
	nyas_enum face; /* cubemaps only */
} nyas_texture_data;

typedef struct nyas_texture {
	nyas_texture_data *images;
	int img_count;
	int width;
	int height;
	nyas_enum type;       /* NYAS_TEXTURE_TYPE */
	nyas_enum format;     /* NYAS_TEXTURE_FORMAT */
	nyas_enum min_filter; /* NYAS_TEXTURE_FILTER */
	nyas_enum mag_filter; /* NYAS_TEXTURE_FILTER */
	nyas_enum wrap_s;     /* NYAS_TEXTURE_WRAP */
	nyas_enum wrap_t;     /* NYAS_TEXTURE_WRAP */
	nyas_enum wrap_r;     /* NYAS_TEXTURE_WRAP */
} nyas_texture;

typedef struct nyas_mesh {
	float *vertices;
	void *indices;
	ptrdiff_t vtx_count;
	ptrdiff_t idx_count;
	int indices_sizeof; /* 2 or 4 */
	nyas_flags vertex_attributes;
} nyas_mesh;

typedef struct nyas_material {
	float *values;
	nyas_handle *textures;
	nyas_handle *cubemaps;
	nyas_handle shader;
} nyas_material;

typedef struct nyas_shader {
	nyas_material shared_data; /* Read-only data for material instances. */
	int shared_values_location;
	int shared_tex_location;
	int shared_cubemap_location;
	int shared_values_count;
	int shared_tex_count;
	int shared_cubemap_count;
	int values_location;
	int tex_location;
	int cubemap_location;
	int values_count;
	int tex_count;
	int cubemap_count;
	nyas_flags vertex_attributes; /* ?? NYAS_FLAG_VA (see: struct nyas_mesh) */
} nyas_shader;

#define NYAS_CONFIG_FRAMEBUFFER_COLOR_TEXTURES 6
typedef struct nyas_framebuffer {
	nyas_handle textures[NYAS_CONFIG_FRAMEBUFFER_COLOR_TEXTURES];
	nyas_handle depth;
	nyas_handle stencil;
} nyas_framebuffer;

typedef struct nyas_draw_state {
	nyas_flags enable_flags;
	nyas_flags disable_flags;
	nyas_enum blend_src_fn;
	nyas_enum blend_dst_fn;
	nyas_enum depth_fn;
	nyas_enum face_culling;
	int viewport_min_x;
	int viewport_min_y;
	int viewport_max_x;
	int viewport_max_y;
	int scissor_min_x;
	int scissor_min_y;
	int scissor_max_x;
	int scissor_max_y;
	float bg_color_r;
	float bg_color_g;
	float bg_color_b;
	float bg_color_a;
} nyas_draw_state;

typedef struct nyas_draw_unit {
	nyas_material material;
	nyas_handle mesh;
} nyas_draw_unit;

typedef struct nyas_draw_command {
	nyas_draw_state state;
	nyas_draw_unit *units;
	ptrdiff_t unit_count;
	nyas_handle framebuffer;
	nyas_handle shader;
} nyas_draw_command;

typedef struct nyas_draw_list {
	nyas_draw_command *commands;
	ptrdiff_t count;
} nyas_draw_list;

#endif // NYAS_DEFS_H
